version: "3.7"

services:
  webhook:
    container_name: webhook-listener
    build: .
    ports:
      - "9999:9999"
    volumes:
      - .:/app
      - /projects/the-menu-backend:/projects/the-menu-backend
      - /root/the-menu-frontend:/root/the-menu-frontend
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.ssh:/root/.ssh:ro

    environment:
      - SECRET_KEY=fvGL5puCNg7Lud4X
    restart: always
